### ISSUE TITLE
"That API call is not allowed for the authenticated user"

### ISSUE THREAD

**Issue by gopi-ar** [rainmattertech/phpkiteconnect#1]
I get this error while trying to access the API with your library, right after the user authenticates successfully and generates a request token:

    "That API call is not allowed for the authenticated user"

Is there something that needs to be enabled on my personal Zerodha a/c to sort this out?

**Comment by vividvilla** [comment]
Please read the documentation carefully. We have mentioned that  `publisher` type apps are only for basket order execution and you won't get full api access. Please create a app of type `Full kite connect` to access all apis.

**Comment by gopi-ar** [comment]
Can you point me to the documentation where this line is mentioned? The point of an API Doc is to state such things explicitly.

Also, how do you expect a developer who's simply testing an API to pay 2000 credits? Shouldn't the API come with the Kite account?

**Comment by rainmattertech** [comment]
@gopi-ar Not sure I understand your question, but Publisher is free of cost. Kite Connect APIs have a monthly subscription fee. The actual API docs (obviously) only deal with technical and not pricing or business details.

But, the difference between various kinds of APIs are clearly explained on the Kite homepage https://kite.trade

Please refer to the various sections -- "Kite Connect for individuals", "Kite Connect for startups", and "Kite Publisher".

Underneath each section, the details are further broken down with concise explanations (how, what, why ..). There's also a "Are there any fees?" section, which is what you seem to be referring to.
